/*
* Organiza a tela ("limpar" tela)
*/
limpar :-
    write('\33\[2J').

% ----------------------------------------------------------------------------------------------- %

pai(philip,charles).
pai(philip,anne).
pai(philip,andrew).
pai(philip,edward).
pai(charles,willian).
pai(charles,harry).
pai(mark_Philips,peter_Philips).
pai(mark_Philips,zara).
pai(andrew,beatrice).
pai(andrew,eugenie).
pai(edward,louise).
pai(edward,james).
pai(willian,george).
pai(willian,charlotte).
pai(willian,louis).
pai(harry,archie).
pai(peter_Philips,savannah).
pai(peter_Philips,isla).
pai(mike,mia).
pai(mike,lena).

mae(elizabeth_II,charles).
mae(elizabeth_II,anne).
mae(elizabeth_II,andrew).
mae(elizabeth_II,edward).
mae(diana,willian).
mae(diana,harry).
mae(anne,peter_Philips).
mae(anne,zara).
mae(sarah,beatrice).
mae(sarah,eugenie).
mae(sophie,louise).
mae(sophie,james).
mae(catherine,george).
mae(catherine,charlotte).
mae(catherine,louis).
mae(meghan,archie).
mae(autumn_Philips,savannah).
mae(autumn_Philips,isla).
mae(zara,mia).
mae(zara,lena).

casados(elizabeth_II,philip).
casados(charles,camilla).
casados(anne,timothy).
casados(andrew,sarah).
casados(edward,sophie).
casados(willian,catherine).
casados(harry,meghan).
casados(peter_Philips,autumn_Philips).
casados(zara,mike).
casados(eugenie,jack).

idade(elizabeth_II,94).
idade(philip,99).
idade(charles,71).
idade(diana,36).
idade(camilla,73).
idade(anne,70).
idade(mark_Philips,71).
idade(timothy,65).
idade(andrew,60).
idade(sarah,60).
idade(edward,56).
idade(sophie,55).
idade(willian,38).
idade(catherine,38).
idade(harry,36).
idade(meghan,39).
idade(peter_Philips,42).
idade(autumn_Philips,42).
idade(zara,39).
idade(mike,39).
idade(beatrice,32).
idade(eugenie,30).
idade(jack,34).
idade(louise,16).
idade(james,12).
idade(george,7).
idade(charlotte,5).
idade(louis,2).
idade(archie,1).
idade(savannah,9).
idade(isla,8).
idade(mia,6).
idade(lena,1)